### Create (POST) - Adicionar um novo cliente
POST http://localhost:3000/clientes
Content-Type: application/json

{
  "senha": "1234",
  "name": "João Sasdasdilva",
  "cpf_cliente": "12745678901",
  "endereco": "Rua dasasdasd Flores, 123",
  "complemento": "Apasdasdto 45",
  "descricao": "Cliente preferencial"
}

### Read (GET) - Obter todos os clientes
GET http://localhost:3000/clientes

### Update (PUT) - Atualizar dados de um cliente por ID
PUT http://localhost:3000/clientes/id
Content-Type: application/json

{
  "senha": "5678",
  "name": "João Souza",
  "cpf_cliente": "12345678901",
  "endereco": "Avenida Central, 456",
  "complemento": "Casa 2",
  "descricao": "Cliente VIP"
}

### Delete (DELETE) - Remover um cliente por ID
DELETE http://localhost:3000/clientes/id