### Create (POST) - Adicionar um novo cliente
POST http://localhost:3000/clientes
Content-Type: application/json

{
  "senha": "1234",
  "name": "João Sasdasdilva",
  "cpf_cliente": "12745678901",
  "endereco": "Rua dasasdasd Flores, 123",
  "complemento": "Apasdasdto 45",
  "descricao": "Cliente preferencial"
}

### Read (GET) - Obter todos os clientes
GET http://localhost:3000/clientes

### Update (PUT) - Atualizar dados de um cliente por ID
PUT http://localhost:3000/clientes/id
Content-Type: application/json

{
  "senha": "5678",
  "name": "João Souza",
  "cpf_cliente": "12345678901",
  "endereco": "Avenida Central, 456",
  "complemento": "Casa 2",
  "descricao": "Cliente VIP"
}

### Delete (DELETE) - Remover um cliente por ID
DELETE http://localhost:3000/clientes/id


### Create (POST) - Adicionar um novo cuidador
POST http://localhost:3000/cuidadores
Content-Type: application/json

{
  "senha": "1234",
  "name": "Maria Silva",
  "cpf_cuidador": "98765432100",
  "endereco": "Rua das Palmeiras, 789",
  "complemento": "Apto 6",
  "descricao": "Cuidadora experiente"
}

### Read (GET) - Obter todos os cuidadores
GET http://localhost:3000/cuidadores

### Update (PUT) - Atualizar dados de um cuidador por ID
PUT http://localhost:3000/cuidadores/id
Content-Type: application/json

{
  "senha": "5678",
  "name": "Maria Oliveira",
  "cpf_cuidador": "12345678901",
  "endereco": "Avenida das Orquídeas, 123",
  "complemento": "Casa 3",
  "descricao": "Cuidadora altamente qualificada"
}

### Delete (DELETE) - Remover um cuidador por ID
DELETE http://localhost:3000/cuidadores/id


### Create (POST) - Adicionar um novo admin
POST http://localhost:3000/admins
Content-Type: application/json

{
  "usuario_admin": "admin123",
  "senha": "adminpass"
}

### Read (GET) - Obter todos os admins
GET http://localhost:3000/admins

### Update (PUT) - Atualizar dados de um admin por ID
PUT http://localhost:3000/admins/id
Content-Type: application/json

{
  "usuario.admin": "novoAdmin",
  "senha": "newadminpass"
}

### Delete (DELETE) - Remover um admin por ID
DELETE http://localhost:3000/admins/id

### Create (POST) - Adicionar um novo servico
POST http://localhost:3000/servicos
Content-Type: application/json

{
  "tipo": "João Sasdasdilva",
  "data": "2024-11-12 14:30:00",
  "id_cliente": "ca3b4969-14dc-4ed8-b39d-c42468f3ba3c",
  "id_cuidador": "e82415b3-116a-4f54-a099-b0601c60024f"
}

### Read (GET) - Obter todos os servicos
GET http://localhost:3000/servicos

### Update (PUT) - Atualizar dados de um servico por ID
PUT http://localhost:3000/servicos/id
Content-Type: application/json

{
  "senha": "5678",
  "name": "João Souza",
  "cpf_cliente": "12345678901",
  "endereco": "Avenida Central, 456",
  "complemento": "Casa 2",
  "descricao": "Cliente VIP"
}

### Delete (DELETE) - Remover um servico por ID
DELETE http://localhost:3000/servicos/id